# Generated by Django 5.2.4 on 2025-09-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lastActive',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='first convo', max_length=255),
            preserve_default=False,
        ),
    ]
