# Generated by Django 5.2.4 on 2025-09-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_message_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='lastActive',
            new_name='last_active',
        ),
    ]
