# Generated by Django 5.2.4 on 2025-11-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_rename_lastactive_conversation_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='airblazo@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='method',
            field=models.CharField(choices=[('google', 'Google')], default='google'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='first_test', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('accent_color', models.CharField(default='blue', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('profileImage', models.CharField(blank=True, max_length=255, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('profile_visible', models.BooleanField(default=True)),
                ('share_data', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('compact_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='chatbot.user')),
            ],
        ),
    ]
