# Generated by Django 5.2.4 on 2025-11-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_user_email_user_method_user_username_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='profileImage',
            new_name='profile_image',
        ),
    ]
