# Generated by Django 5.2.4 on 2025-12-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_profileimage_preferences_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
