# Generated by Django 5.2.4 on 2025-12-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_exercise_exercisefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
