# Generated by Django 5.2.4 on 2025-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_conversation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='correctness',
            field=models.IntegerField(blank=True, choices=[(0, 'Incorrect'), (1, 'Nearly'), (2, 'Correct')], null=True),
        ),
        migrations.AddField(
            model_name='exercisefile',
            name='user_submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
