# Generated by Django 5.2.4 on 2025-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_exercise_correctness_exercisefile_user_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
