# Generated by Django 5.2.4 on 2025-12-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_exercise_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
