# Generated by Django 5.2.4 on 2026-01-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_exercise_tags_exercise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='tab_size',
            field=models.IntegerField(default=2),
        ),
    ]
