# Generated by Django 5.2.4 on 2026-01-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_preferences_tab_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
