# Generated by Django 5.2.4 on 2026-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_exercise_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_limit',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='token_used',
            field=models.IntegerField(default=0),
        ),
    ]
