# Generated by Django 5.2.4 on 2026-01-23 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_user_membership_user_membership_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
