# Generated by Django 5.2.4 on 2026-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_alter_user_membership_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
