# Generated by Django 5.2.4 on 2026-01-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_user_membership_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_used', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_remaining', models.IntegerField()),
                ('action', models.CharField(choices=[('router', 'Message'), ('instructor', 'Message with lesson generated'), ('exercise_evaluator', 'Exercise marking'), ('exercise_generator', 'Exercise Generation')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.user')),
            ],
        ),
    ]
