# Generated by Django 5.2.4 on 2026-02-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='free_feedback_for_exercises_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
