# Generated by Django 5.2.4 on 2026-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_user_stripe_customer_id_alter_user_token_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
