# Generated by Django 5.2.4 on 2026-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_user_subscription_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='token_limit',
            field=models.IntegerField(default=100000),
        ),
    ]
