# Generated by Django 5.2.4 on 2026-09-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_alter_preferences_tab_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='speech_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='voice_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferences',
            name='voice_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='SpeechClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('summary', 'Summary'), ('full', 'Full')], max_length=10)),
                ('voice_id', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=64)),
                ('text_hash', models.CharField(max_length=64)),
                ('characters', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=10)),
                ('storage_key', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('marks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_clips', to='chatbot.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_clips', to='chatbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_hit', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='chatbot.speechclip')),
            ],
        ),
        migrations.AddIndex(
            model_name='speechclip',
            index=models.Index(fields=['user', 'created_at'], name='chatbot_spe_user_id_28206d_idx'),
        ),
        migrations.AddIndex(
            model_name='speechclip',
            index=models.Index(fields=['created_at'], name='chatbot_spe_created_70cca6_idx'),
        ),
        migrations.AddConstraint(
            model_name='speechclip',
            constraint=models.UniqueConstraint(fields=('message', 'scope', 'voice_id', 'model_id', 'text_hash'), name='unique_speech_clip'),
        ),
    ]
